# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: candidate_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='candidate_info.proto',
  package='ai_custom_service',
  syntax='proto3',
  serialized_options=_b('\n\024cn.haolie.core.protoB\016AiProjectProtoP\001'),
  serialized_pb=_b('\n\x14\x63\x61ndidate_info.proto\x12\x11\x61i_custom_service\"X\n\rChatChildNode\x12\x0e\n\x06\x63hoice\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12)\n\x04node\x18\x03 \x01(\x0b\x32\x1b.ai_custom_service.ChatNode\"e\n\x08\x43hatNode\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x13\n\x0bquestion_id\x18\x02 \x01(\x05\x12\x32\n\x08\x63hildren\x18\x03 \x03(\x0b\x32 .ai_custom_service.ChatChildNode\"V\n\x0c\x43hatTemplate\x12)\n\x04root\x18\x01 \x01(\x0b\x32\x1b.ai_custom_service.ChatNode\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0f\n\x07task_id\x18\x03 \x01(\x05\"2\n\x0fQuestionRequest\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\"\xb7\x01\n\x10QuestionResponse\x12\x12\n\nquesion_id\x18\x01 \x01(\x05\x12\x10\n\x08question\x18\x02 \x01(\t\x12;\n\x06status\x18\x03 \x01(\x0e\x32+.ai_custom_service.QuestionResponse.eStatus\x12\x0f\n\x07task_id\x18\x04 \x01(\x05\"/\n\x07\x65Status\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\n\n\x06\x43LOSED\x10\x02\"+\n\x19\x42uildChatTemplateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"+\n\x18\x43loseChatTemplateRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"+\n\x19\x43loseChatTemplateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xbf\x02\n\x0b\x43hatService\x12\x64\n\x11\x42uildChatTemplate\x12\x1f.ai_custom_service.ChatTemplate\x1a,.ai_custom_service.BuildChatTemplateResponse\"\x00\x12p\n\x11\x43loseChatTemplate\x12+.ai_custom_service.CloseChatTemplateRequest\x1a,.ai_custom_service.CloseChatTemplateResponse\"\x00\x12X\n\x0bGetQuestion\x12\".ai_custom_service.QuestionRequest\x1a#.ai_custom_service.QuestionResponse\"\x00\x42(\n\x14\x63n.haolie.core.protoB\x0e\x41iProjectProtoP\x01\x62\x06proto3')
)



_QUESTIONRESPONSE_ESTATUS = _descriptor.EnumDescriptor(
  name='eStatus',
  full_name='ai_custom_service.QuestionResponse.eStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=513,
  serialized_end=560,
)
_sym_db.RegisterEnumDescriptor(_QUESTIONRESPONSE_ESTATUS)


_CHATCHILDNODE = _descriptor.Descriptor(
  name='ChatChildNode',
  full_name='ai_custom_service.ChatChildNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='choice', full_name='ai_custom_service.ChatChildNode.choice', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keys', full_name='ai_custom_service.ChatChildNode.keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node', full_name='ai_custom_service.ChatChildNode.node', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=131,
)


_CHATNODE = _descriptor.Descriptor(
  name='ChatNode',
  full_name='ai_custom_service.ChatNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='ai_custom_service.ChatNode.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='question_id', full_name='ai_custom_service.ChatNode.question_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='ai_custom_service.ChatNode.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=234,
)


_CHATTEMPLATE = _descriptor.Descriptor(
  name='ChatTemplate',
  full_name='ai_custom_service.ChatTemplate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='ai_custom_service.ChatTemplate.root', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='ai_custom_service.ChatTemplate.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ai_custom_service.ChatTemplate.task_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=322,
)


_QUESTIONREQUEST = _descriptor.Descriptor(
  name='QuestionRequest',
  full_name='ai_custom_service.QuestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='ai_custom_service.QuestionRequest.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ai_custom_service.QuestionRequest.task_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=374,
)


_QUESTIONRESPONSE = _descriptor.Descriptor(
  name='QuestionResponse',
  full_name='ai_custom_service.QuestionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quesion_id', full_name='ai_custom_service.QuestionResponse.quesion_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='question', full_name='ai_custom_service.QuestionResponse.question', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ai_custom_service.QuestionResponse.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ai_custom_service.QuestionResponse.task_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUESTIONRESPONSE_ESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=560,
)


_BUILDCHATTEMPLATERESPONSE = _descriptor.Descriptor(
  name='BuildChatTemplateResponse',
  full_name='ai_custom_service.BuildChatTemplateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ai_custom_service.BuildChatTemplateResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=605,
)


_CLOSECHATTEMPLATEREQUEST = _descriptor.Descriptor(
  name='CloseChatTemplateRequest',
  full_name='ai_custom_service.CloseChatTemplateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='ai_custom_service.CloseChatTemplateRequest.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=650,
)


_CLOSECHATTEMPLATERESPONSE = _descriptor.Descriptor(
  name='CloseChatTemplateResponse',
  full_name='ai_custom_service.CloseChatTemplateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ai_custom_service.CloseChatTemplateResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=695,
)

_CHATCHILDNODE.fields_by_name['node'].message_type = _CHATNODE
_CHATNODE.fields_by_name['children'].message_type = _CHATCHILDNODE
_CHATTEMPLATE.fields_by_name['root'].message_type = _CHATNODE
_QUESTIONRESPONSE.fields_by_name['status'].enum_type = _QUESTIONRESPONSE_ESTATUS
_QUESTIONRESPONSE_ESTATUS.containing_type = _QUESTIONRESPONSE
DESCRIPTOR.message_types_by_name['ChatChildNode'] = _CHATCHILDNODE
DESCRIPTOR.message_types_by_name['ChatNode'] = _CHATNODE
DESCRIPTOR.message_types_by_name['ChatTemplate'] = _CHATTEMPLATE
DESCRIPTOR.message_types_by_name['QuestionRequest'] = _QUESTIONREQUEST
DESCRIPTOR.message_types_by_name['QuestionResponse'] = _QUESTIONRESPONSE
DESCRIPTOR.message_types_by_name['BuildChatTemplateResponse'] = _BUILDCHATTEMPLATERESPONSE
DESCRIPTOR.message_types_by_name['CloseChatTemplateRequest'] = _CLOSECHATTEMPLATEREQUEST
DESCRIPTOR.message_types_by_name['CloseChatTemplateResponse'] = _CLOSECHATTEMPLATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatChildNode = _reflection.GeneratedProtocolMessageType('ChatChildNode', (_message.Message,), dict(
  DESCRIPTOR = _CHATCHILDNODE,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.ChatChildNode)
  ))
_sym_db.RegisterMessage(ChatChildNode)

ChatNode = _reflection.GeneratedProtocolMessageType('ChatNode', (_message.Message,), dict(
  DESCRIPTOR = _CHATNODE,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.ChatNode)
  ))
_sym_db.RegisterMessage(ChatNode)

ChatTemplate = _reflection.GeneratedProtocolMessageType('ChatTemplate', (_message.Message,), dict(
  DESCRIPTOR = _CHATTEMPLATE,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.ChatTemplate)
  ))
_sym_db.RegisterMessage(ChatTemplate)

QuestionRequest = _reflection.GeneratedProtocolMessageType('QuestionRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUESTIONREQUEST,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.QuestionRequest)
  ))
_sym_db.RegisterMessage(QuestionRequest)

QuestionResponse = _reflection.GeneratedProtocolMessageType('QuestionResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUESTIONRESPONSE,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.QuestionResponse)
  ))
_sym_db.RegisterMessage(QuestionResponse)

BuildChatTemplateResponse = _reflection.GeneratedProtocolMessageType('BuildChatTemplateResponse', (_message.Message,), dict(
  DESCRIPTOR = _BUILDCHATTEMPLATERESPONSE,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.BuildChatTemplateResponse)
  ))
_sym_db.RegisterMessage(BuildChatTemplateResponse)

CloseChatTemplateRequest = _reflection.GeneratedProtocolMessageType('CloseChatTemplateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLOSECHATTEMPLATEREQUEST,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.CloseChatTemplateRequest)
  ))
_sym_db.RegisterMessage(CloseChatTemplateRequest)

CloseChatTemplateResponse = _reflection.GeneratedProtocolMessageType('CloseChatTemplateResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLOSECHATTEMPLATERESPONSE,
  __module__ = 'candidate_info_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.CloseChatTemplateResponse)
  ))
_sym_db.RegisterMessage(CloseChatTemplateResponse)


DESCRIPTOR._options = None

_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='ai_custom_service.ChatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=698,
  serialized_end=1017,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildChatTemplate',
    full_name='ai_custom_service.ChatService.BuildChatTemplate',
    index=0,
    containing_service=None,
    input_type=_CHATTEMPLATE,
    output_type=_BUILDCHATTEMPLATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseChatTemplate',
    full_name='ai_custom_service.ChatService.CloseChatTemplate',
    index=1,
    containing_service=None,
    input_type=_CLOSECHATTEMPLATEREQUEST,
    output_type=_CLOSECHATTEMPLATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetQuestion',
    full_name='ai_custom_service.ChatService.GetQuestion',
    index=2,
    containing_service=None,
    input_type=_QUESTIONREQUEST,
    output_type=_QUESTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
