# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='ai_custom_service',
  syntax='proto3',
  serialized_pb=_b('\n\ntest.proto\x12\x11\x61i_custom_service\"\x18\n\x08PathKeys\x12\x0c\n\x04keys\x18\x01 \x03(\t\"\xaf\x02\n\x08\x43hatNode\x12\n\n\x02qs\x18\x01 \x01(\t\x12\r\n\x05qs_id\x18\x02 \x01(\x05\x12\x33\n\x04keys\x18\x03 \x03(\x0b\x32%.ai_custom_service.ChatNode.KeysEntry\x12;\n\x08\x63hildren\x18\x04 \x03(\x0b\x32).ai_custom_service.ChatNode.ChildrenEntry\x1aH\n\tKeysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.ai_custom_service.PathKeys:\x02\x38\x01\x1aL\n\rChildrenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.ai_custom_service.ChatNode:\x02\x38\x01\x42(\n\x14\x63n.haolie.core.protoB\x0e\x41iProjectProtoP\x01\x62\x06proto3')
)




_PATHKEYS = _descriptor.Descriptor(
  name='PathKeys',
  full_name='ai_custom_service.PathKeys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='ai_custom_service.PathKeys.keys', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=57,
)


_CHATNODE_KEYSENTRY = _descriptor.Descriptor(
  name='KeysEntry',
  full_name='ai_custom_service.ChatNode.KeysEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ai_custom_service.ChatNode.KeysEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ai_custom_service.ChatNode.KeysEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=285,
)

_CHATNODE_CHILDRENENTRY = _descriptor.Descriptor(
  name='ChildrenEntry',
  full_name='ai_custom_service.ChatNode.ChildrenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ai_custom_service.ChatNode.ChildrenEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ai_custom_service.ChatNode.ChildrenEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=363,
)

_CHATNODE = _descriptor.Descriptor(
  name='ChatNode',
  full_name='ai_custom_service.ChatNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qs', full_name='ai_custom_service.ChatNode.qs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qs_id', full_name='ai_custom_service.ChatNode.qs_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='ai_custom_service.ChatNode.keys', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='ai_custom_service.ChatNode.children', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHATNODE_KEYSENTRY, _CHATNODE_CHILDRENENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=363,
)

_CHATNODE_KEYSENTRY.fields_by_name['value'].message_type = _PATHKEYS
_CHATNODE_KEYSENTRY.containing_type = _CHATNODE
_CHATNODE_CHILDRENENTRY.fields_by_name['value'].message_type = _CHATNODE
_CHATNODE_CHILDRENENTRY.containing_type = _CHATNODE
_CHATNODE.fields_by_name['keys'].message_type = _CHATNODE_KEYSENTRY
_CHATNODE.fields_by_name['children'].message_type = _CHATNODE_CHILDRENENTRY
DESCRIPTOR.message_types_by_name['PathKeys'] = _PATHKEYS
DESCRIPTOR.message_types_by_name['ChatNode'] = _CHATNODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathKeys = _reflection.GeneratedProtocolMessageType('PathKeys', (_message.Message,), dict(
  DESCRIPTOR = _PATHKEYS,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.PathKeys)
  ))
_sym_db.RegisterMessage(PathKeys)

ChatNode = _reflection.GeneratedProtocolMessageType('ChatNode', (_message.Message,), dict(

  KeysEntry = _reflection.GeneratedProtocolMessageType('KeysEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHATNODE_KEYSENTRY,
    __module__ = 'test_pb2'
    # @@protoc_insertion_point(class_scope:ai_custom_service.ChatNode.KeysEntry)
    ))
  ,

  ChildrenEntry = _reflection.GeneratedProtocolMessageType('ChildrenEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHATNODE_CHILDRENENTRY,
    __module__ = 'test_pb2'
    # @@protoc_insertion_point(class_scope:ai_custom_service.ChatNode.ChildrenEntry)
    ))
  ,
  DESCRIPTOR = _CHATNODE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ai_custom_service.ChatNode)
  ))
_sym_db.RegisterMessage(ChatNode)
_sym_db.RegisterMessage(ChatNode.KeysEntry)
_sym_db.RegisterMessage(ChatNode.ChildrenEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024cn.haolie.core.protoB\016AiProjectProtoP\001'))
_CHATNODE_KEYSENTRY.has_options = True
_CHATNODE_KEYSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_CHATNODE_CHILDRENENTRY.has_options = True
_CHATNODE_CHILDRENENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
