#python qs_matching.py test_get_similarity 谁
#python qs_matching.py test_get_similarity 想干啥
#python qs_matching.py test_get_similarity 滚
#python qs_matching.py test_get_similarity 一个月多少钱
#python qs_matching.py test_get_similarity 年薪多少
#python qs_matching.py test_get_similarity 你推荐的是哪家公司
#python qs_matching.py test_get_similarity 我很满意
#python qs_matching.py test_get_similarity 你有什么事吗
#python qs_matching.py test_get_similarity 你说的是哪家
#python qs_matching.py test_get_similarity 工作地点在哪
#python qs_matching.py test_get_similarity 钱多么
#python qs_matching.py test_get_similarity 工作累吗
#python qs_matching.py test_get_similarity 你爱我吗
#python qs_matching.py test_get_similarity 你是？
#python qs_matching.py test_get_similarity 你谁啊
#python qs_matching.py test_get_similarity 呵呵
#python qs_matching.py test_get_similarity 大哥哥好不好
python qs_matching.py test_get_similarity 公司在什么位置
python qs_matching.py test_get_similarity 在什么位置
#python qs_matching.py test_get_similarity 我就想试试句子长度很长时，你的识别速度怎么样，会不会很慢啊，如果慢，会是什么原因呢？