python qs_matching.py test_get_similarity 谁
python qs_matching.py test_get_similarity 想干啥
python qs_matching.py test_get_similarity 滚
python qs_matching.py test_get_similarity 一个月多少钱
python qs_matching.py test_get_similarity 年薪多少
python qs_matching.py test_get_similarity 你推荐的是哪家公司
python qs_matching.py test_get_similarity 我很满意
python qs_matching.py test_get_similarity 你有什么事吗
python qs_matching.py test_get_similarity 你说的是哪家
python qs_matching.py test_get_similarity 工作地点在哪
python qs_matching.py test_get_similarity 钱多么
python qs_matching.py test_get_similarity 工作累吗
python qs_matching.py test_get_similarity 你爱我吗
python qs_matching.py test_get_similarity 你是？
python qs_matching.py test_get_similarity 你谁啊
python qs_matching.py test_get_similarity 呵呵
python qs_matching.py test_get_similarity 大哥哥好不好
python qs_matching.py test_get_similarity 公司在什么位置
python qs_matching.py test_get_similarity 在什么位置
python qs_matching.py test_get_similarity 为什么会有我的简历
python qs_matching.py test_get_similarity 为什么会有我的联系方式
python qs_matching.py test_get_similarity 你是哪个公司的
python qs_matching.py test_get_similarity 微信号不方便提供，电话是否可以
python qs_matching.py test_get_similarity 微信号不方便提供，邮件是否可以
python qs_matching.py test_get_similarity 不想你推送相关信息，想直接沟通这份工作相关的内容可以么
python qs_matching.py test_get_similarity 可以稍后再给我打个电话吗，我现在有事儿
python qs_matching.py test_get_similarity 推荐的工作不是未来想要的发展方向，是否有别的岗位可以推荐
python qs_matching.py test_get_similarity 这份工作的税后工资及公司福利政策
python qs_matching.py test_get_similarity 未来的晋升渠道跟发展是什么样子的
python qs_matching.py test_get_similarity 贵司是按最低标准缴纳五险一金还是全额工资
python qs_matching.py test_get_similarity 有避税政策么
python qs_matching.py test_get_similarity 办公地址是在哪里
python qs_matching.py test_get_similarity 请问你说的合适的机会是什么？
python qs_matching.py test_get_similarity 方便，请问有什么事吗？
python qs_matching.py test_get_similarity 现在不太方便，请问可以六点半小时后或者晚点再打过来吗？
python qs_matching.py test_get_similarity 不是的，我不记得我的微信号了怎么办？
python qs_matching.py test_get_similarity 这个工作一般薪资是多少钱呢？
python qs_matching.py test_get_similarity 这个工作在行业内平均薪资是多少钱呢？
python qs_matching.py test_get_similarity 请问我某某年工作经验，应该要多少薪资呢？
python qs_matching.py test_get_similarity 为什么要了解我的薪资？
python qs_matching.py test_get_similarity 什么机会
python qs_matching.py test_get_similarity 啥机会
python qs_matching.py test_get_similarity 嗯
python qs_matching.py test_get_similarity 方便
python qs_matching.py test_get_similarity 嗯，方便
python qs_matching.py test_get_similarity 嗯，不方便
python qs_matching.py test_get_similarity 不方便
#python qs_matching.py test_get_similarity 我就想试试句子长度很长时，你的识别速度怎么样，会不会很慢啊，如果慢，会是什么原因呢？